FROM mcr.microsoft.com/devcontainers/python:1-3.12-bullseye

ADD https://truststore.pki.us-gov-west-1.rds.amazonaws.com/global/global-bundle.pem \
    /usr/local/share/ca-certificates/global-bundle.pem
